CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_EMPLEADO INT NOT NULL, -- FK a tu tabla actual de empleados
    ID_ROL INT NOT NULL,      -- FK a la tabla de roles
    USUARIO VARCHAR(50) NOT NULL UNIQUE, 
    CONTRASENA VARCHAR(255) NOT NULL, -- Aquí irá el Hash (BCrypt)
    ESTADO ENUM('ACTIVO', 'INACTIVO') DEFAULT 'ACTIVO',
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USUARIO_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
) ENGINE = InnoDB;  
USE BALBU_TECH;
CREATE INDEX IX_USER ON USUARIOS (USUARIO);


-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------[Store procedure}-------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------    
SELECT * FROM `USUARIOS`;
--INSERTAR

DELIMITER //
DROP PROCEDURE IF EXISTS SP_INSERTAR_USUARIO ;

CREATE OR REPLACE PROCEDURE SP_INSERTAR_USUARIO(
    IN P_ID_EMPLEADO INT,
    IN P_ID_ROL      INT,
    IN P_USUARIO     VARCHAR(50),
    IN P_HASH_CLAVE  VARCHAR(255) -- Nombre cambiado para mayor claridad
)
proc_label: BEGIN
    DECLARE v_usuario_limpio VARCHAR(50);
    DECLARE v_nombre_empleado VARCHAR(100);

    SELECT NOMBRE INTO v_nombre_empleado FROM EMPLEADOS WHERE ID_EMPLEADO = P_ID_EMPLEADO;
    IF v_nombre_empleado IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EMPLEADO NO ENCONTRADO.';
        LEAVE proc_label;
    END IF;

    SET v_usuario_limpio = LOWER(REPLACE(TRIM(P_USUARIO), ' ', '.'));

    IF EXISTS (SELECT 1 FROM USUARIOS WHERE USUARIO = v_usuario_limpio) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: USUARIO YA EN USO.';
        LEAVE proc_label;
    END IF;

    -- Aquí guardamos el HASH directamente
    INSERT INTO USUARIOS (ID_EMPLEADO, ID_ROL, USUARIO, CONTRASENA)
    VALUES (P_ID_EMPLEADO, P_ID_ROL, v_usuario_limpio, P_HASH_CLAVE);

    SELECT CONCAT('EXITO: USUARIO "', v_usuario_limpio, '" CREADO.') AS MENSAJE;
END ;

DELIMITER ;
use BALBU_TECH;

--ACTUALIZAR
use BALBU_TECH;
DELIMITER //
DROP PROCEDURE IF EXISTS SP_ACTUALIZAR_USUARIO ;

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_USUARIO(
    IN P_ID_USUARIO   INT,
    IN P_USUARIO      VARCHAR(50),
    IN P_ID_ROL       INT,
    IN P_ID_EMPLEADO  INT
)
proc_label: BEGIN
    DECLARE v_usuario_limpio VARCHAR(50);

    IF NOT EXISTS (SELECT 1 FROM `USUARIOS` WHERE `ID_USUARIO` = P_ID_USUARIO) THEN 
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: USUARIO NO EXISTE.';
        LEAVE proc_label;
    END IF;

    -- Lógica de limpieza solo si el usuario cambió
    IF P_USUARIO IS NOT NULL THEN
        SET v_usuario_limpio = LOWER(TRIM(P_USUARIO));
    END IF;

    UPDATE `USUARIOS` 
    SET 
        `USUARIO`     = COALESCE(v_usuario_limpio, `USUARIO`),
        -- El COALESCE aquí permite que, si enviamos NULL desde C++, se conserve el hash anterior
        `ID_EMPLEADO` = COALESCE(P_ID_EMPLEADO, `ID_EMPLEADO`),
        `ID_ROL`      = COALESCE(P_ID_ROL, `ID_ROL`)
    WHERE `ID_USUARIO` = P_ID_USUARIO;

    SELECT 'EXITO: DATOS ACTUALIZADOS.' AS MENSAJE;
END;

DELIMITER ;

---TOGGLER PARA ESTADO
DELIMITER //

DROP PROCEDURE IF EXISTS SP_TOGGLE_ESTADO_USUARIO;

CREATE PROCEDURE SP_TOGGLE_ESTADO_USUARIO(
    IN P_ID_USUARIO INT
)
proc_label: BEGIN
    -- VARIABLES PARA CAPTURAR LA INFO ACTUAL
    DECLARE v_USUARIO_NOMBRE VARCHAR(50);
    DECLARE v_ESTADO_ACTUAL  VARCHAR(20);
    DECLARE v_NUEVO_ESTADO   VARCHAR(20);

    -- 1. VALIDAR QUE EL USUARIO EXISTA
    IF NOT EXISTS (SELECT 1 FROM `USUARIOS` WHERE `ID_USUARIO` = P_ID_USUARIO) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL USUARIO NO EXISTE.';
        LEAVE proc_label;
    END IF;

    -- 2. OBTENER ESTADO Y NOMBRE ACTUAL
    SELECT `USUARIO`, `ESTADO` INTO v_USUARIO_NOMBRE, v_ESTADO_ACTUAL 
    FROM `USUARIOS` 
    WHERE `ID_USUARIO` = P_ID_USUARIO;

    -- 3. LÓGICA DEL "INTERRUPTOR" (TOGGLE)
    IF v_ESTADO_ACTUAL = 'ACTIVO' THEN
        SET v_NUEVO_ESTADO = 'INACTIVO';
    ELSE 
        SET v_NUEVO_ESTADO = 'ACTIVO';
    END IF;

    -- 4. APLICAR EL CAMBIO
    UPDATE `USUARIOS` 
    SET `ESTADO` = v_NUEVO_ESTADO 
    WHERE `ID_USUARIO` = P_ID_USUARIO;

    -- 5. MENSAJE FINAL
    SELECT CONCAT(
        'USUARIO: "', v_USUARIO_NOMBRE, 
        '" - CAMBIO DE: ', v_ESTADO_ACTUAL, 
        ' A: ', v_NUEVO_ESTADO
    ) AS MENSAJE;

END ;

DELIMITER ;


--BUSCAR CON FILTRO
DELIMITER //

DROP PROCEDURE IF EXISTS SP_BUSCAR_USUARIOS_FILTRADO ;

CREATE PROCEDURE SP_BUSCAR_USUARIOS_FILTRADO(
    IN P_BUSQUEDA VARCHAR(100)
)
BEGIN
    SELECT
        U.ID_USUARIO,
        U.USUARIO,
        E.NOMBRE AS EMPLEADO,
        R.NOMBRE_ROL AS ROL,
        U.ESTADO
    FROM `USUARIOS` U
    INNER JOIN `ROLES` R ON U.ID_ROL = R.ID_ROL
    INNER JOIN `EMPLEADOS` E ON E.ID_EMPLEADO = U.ID_EMPLEADO
    WHERE (P_BUSQUEDA IS NULL OR P_BUSQUEDA = ''
           OR U.USUARIO LIKE CONCAT('%', P_BUSQUEDA, '%')
           OR E.NOMBRE LIKE CONCAT('%', P_BUSQUEDA, '%'))
    ORDER BY U.USUARIO ASC;
END ;

DELIMITER ;

CALL SP_BUSCAR_USUARIOS_FILTRADO('ANTHONY');
---CAMBIAR CONTRASENA

DELIMITER //
DROP PROCEDURE IF EXISTS SP_CAMBIAR_CONTRASENA ;
CREATE PROCEDURE SP_CAMBIAR_CONTRASENA(
    IN P_ID_USUARIO INT,
    IN P_CLAVE_ACTUAL_HASH VARCHAR(255),
    IN P_CLAVE_NUEVA_HASH  VARCHAR(255)
)
proc_label: BEGIN
    DECLARE v_usuario_nombre VARCHAR(50);

    -- 1. Validar existencia y que la clave actual sea correcta
    SELECT `USUARIO` INTO v_usuario_nombre 
    FROM `USUARIOS` 
    WHERE `ID_USUARIO` = P_ID_USUARIO 
      AND `CONTRASENA` = P_CLAVE_ACTUAL_HASH;

    IF v_usuario_nombre IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: USUARIO NO ENCONTRADO O CLAVE ACTUAL INCORRECTA.';
        LEAVE proc_label;
    END IF;

    -- 2. Actualizar a la nueva clave
    UPDATE `USUARIOS` 
    SET `CONTRASENA` = P_CLAVE_NUEVA_HASH
    WHERE `ID_USUARIO` = P_ID_USUARIO;

    -- 3. Mensaje de éxito incluyendo el ID y el nombre del usuario
    SELECT CONCAT(
        'EXITO: CONTRASEÑA ACTUALIZADA PARA EL USUARIO: "', 
        v_usuario_nombre, 
        '" (ID: ', P_ID_USUARIO, ')'
    ) AS MENSAJE;

END ;
DELIMITER ;


SELECT * from USUARIOS;


USE BALBU_TECH;


--Sp para mostrar antes de hacer ciertas acciones. Van en el modulo de  usuarios

-- uso de agregar un usuario
DELIMITER//

DROP PROCEDURE IF EXISTS PARA_INSERTAR_USUARIOS;

CREATE PROCEDURE PARA_INSERTAR_USUARIOS()
BEGIN

SELECT ID_ROL , `NOMBRE_ROL` 
FROM ROLES
ORDER BY ID_ROL ASC;


SELECT ID_EMPLEADO , NOMBRE 
FROM EMPLEADOS
ORDER BY `ID_EMPLEADO` ASC;

END;

CALL PARA_INSERTAR_USUARIOS();

DELIMITER;





DELIMITER // 

DROP PROCEDURE IF EXISTS PARA_ACTUALIZAR_USUARIOS;

CREATE PROCEDURE PARA_ACTUALIZAR_USUARIOS()
BEGIN
SELECT 
U.ID_USUARIO, U.USUARIO AS NOMBRE_USUARIO,
R.ID_ROL , R.NOMBRE_ROL AS NOMBRE_ROL,
E.ID_EMPLEADO, E.NOMBRE AS NOMBRE_EMPLEADO
FROM
USUARIOS AS U
LEFT JOIN 
ROLES AS R ON
U.ID_ROL = R.ID_ROL
LEFT JOIN EMPLEADOS AS E
ON
U.ID_EMPLEADO = E.ID_EMPLEADO
ORDER BY 
U.ID_USUARIO ASC,
E.ID_EMPLEADO ASC,
R.ID_ROL ASC;

END;

CALL PARA_ACTUALIZAR_USUARIOS();

DELIMITER;

