-- Active: 1775068811273@@127.0.0.1@3306@BALBU_TECH
CREATE TABLE ASIGNACIONES_RECLAMOS (
    ID_ASIGNACION INT NOT NULL AUTO_INCREMENT,
    ID_RECLAMO_GARAN INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    FECHA_ASIGNACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_FINALIZACION DATETIME NULL,
    PRIORIDAD ENUM('BAJA', 'MEDIA', 'ALTA', 'URGENTE') DEFAULT 'MEDIA',
    ESTADO_ASIGNACION ENUM('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'CANCELADO') DEFAULT 'PENDIENTE',
    OBSERVACIONES VARCHAR(255),
    PRIMARY KEY (ID_ASIGNACION),
    -- Índices para búsqueda rápida
    INDEX IDX_EMPLEADO_FECHA (ID_EMPLEADO, FECHA_ASIGNACION),
    -- Relaciones
    CONSTRAINT FK_ASIGNACION_RECLAMO FOREIGN KEY (ID_RECLAMO_GARAN) REFERENCES RECLAMOS_GARANTIAS (ID_RECLAMO_GARAN) ON DELETE CASCADE,
    CONSTRAINT FK_ASIGNACION_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (ID_EMPLEADO)
) ENGINE = InnoDB;

ALTER TABLE ASIGNACIONES_RECLAMOS 
ADD CONSTRAINT CHK_FECHAS_VALIDAS 
CHECK (FECHA_FINALIZACION >= FECHA_ASIGNACION);



CREATE INDEX IDX_ASIGNACIONES_EMPLEADO_FECHA 
ON ASIGNACIONES_RECLAMOS (ID_EMPLEADO, FECHA_ASIGNACION);


-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------[Store procedure}-------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------   

---COMIENZA AISGNACION
DELIMITER //

DROP PROCEDURE IF EXISTS SP_ASIGNAR_TECNICO_RECLAMO; 

CREATE PROCEDURE SP_ASIGNAR_TECNICO_RECLAMO(
    IN P_ID_RECLAMO INT,
    IN P_ID_EMPLEADO INT,
    IN P_PRIORIDAD ENUM('BAJA', 'MEDIA', 'ALTA', 'URGENTE'),
    IN P_OBSERVACIONES VARCHAR(255)
)
proc_label: BEGIN
    DECLARE V_ESTADO_RECLAMO VARCHAR(20);

    -- 1. Validar que el reclamo exista y esté pendiente
    SELECT ESTADO INTO V_ESTADO_RECLAMO 
    FROM RECLAMOS_GARANTIAS 
    WHERE ID_RECLAMO_GARAN = P_ID_RECLAMO;

    IF V_ESTADO_RECLAMO IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: RECLAMO NO ENCONTRADO.';
        LEAVE proc_label;
    END IF;

    IF V_ESTADO_RECLAMO <> 'PENDIENTE' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: SOLO SE PUEDEN ASIGNAR TÉCNICOS A RECLAMOS PENDIENTES.';
        LEAVE proc_label;
    END IF;

    -- 2. Insertar la asignación con la nueva estructura
    INSERT INTO ASIGNACIONES_RECLAMOS (
        ID_RECLAMO_GARAN, 
        ID_EMPLEADO, 
        PRIORIDAD, 
        ESTADO_ASIGNACION, 
        OBSERVACIONES
    )
    VALUES (
        P_ID_RECLAMO, 
        P_ID_EMPLEADO, 
        P_PRIORIDAD, 
        'EN_PROCESO', 
        P_OBSERVACIONES
    );
    
    -- 3. Actualizar el estado del reclamo principal
    UPDATE RECLAMOS_GARANTIAS 
    SET ESTADO = 'EN_PROCESO' 
    WHERE ID_RECLAMO_GARAN = P_ID_RECLAMO;
    
    SELECT 'EXITO: TÉCNICO ASIGNADO CORRECTAMENTE.' AS MENSAJE;
END;

DELIMITER ;

---FINALIZAR 

DELIMITER //

DROP PROCEDURE IF EXISTS SP_FINALIZAR_RECLAMO;

CREATE PROCEDURE SP_FINALIZAR_RECLAMO(
    IN P_ID_ASIGNACION INT,
    IN P_OBSERVACIONES_FINALES VARCHAR(255)
)
BEGIN
    -- 1. Actualizamos la asignación
    UPDATE ASIGNACIONES_RECLAMOS 
    SET ESTADO_ASIGNACION = 'COMPLETADO',
        FECHA_FINALIZACION = NOW(),
        OBSERVACIONES = CONCAT(OBSERVACIONES, ' | Nota final: ', P_OBSERVACIONES_FINALES)
    WHERE ID_ASIGNACION = P_ID_ASIGNACION;

    -- 2. Actualizamos el reclamo general a 'CERRADO'
    UPDATE RECLAMOS_GARANTIAS
    SET ESTADO = 'CERRADO'
    WHERE ID_RECLAMO_GARAN = (SELECT ID_RECLAMO_GARAN FROM ASIGNACIONES_RECLAMOS WHERE ID_ASIGNACION = P_ID_ASIGNACION);
    
    SELECT 'EXITO: RECLAMO FINALIZADO Y CERRADO.' AS MENSAJE;
END;

DELIMITER ;