CREATE TABLE DETALLE_REPARACIONES (
    ID_REPARACION INT NOT NULL AUTO_INCREMENT,
    ID_ASIGNACION INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FECHA_ACCION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACCION_REALIZADA VARCHAR(255) NOT NULL,
    REPUESTO_UTILIZADO VARCHAR(100),
    COSTO_REPUESTO DECIMAL(10,2) DEFAULT 0.00,
    TIEMPO_EMPLEADO_MIN INT DEFAULT 0,
    ESTADO_AVANCE VARCHAR(20) DEFAULT 'EN_PROCESO',
    RUTA_EVIDENCIA VARCHAR(255) NULL,
    PRIMARY KEY (ID_REPARACION),
    CONSTRAINT FK_REPARACION_ASIGNACION FOREIGN KEY (ID_ASIGNACION) REFERENCES ASIGNACIONES_RECLAMOS (ID_ASIGNACION) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
) ENGINE = InnoDB;




-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------[Store procedure}-------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------   


DELIMITER //

DROP PROCEDURE IF EXISTS SP_REGISTRAR_AVANCE_REPARACION;

CREATE PROCEDURE SP_REGISTRAR_AVANCE_REPARACION(
    IN P_ID_ASIGNACION INT,
    IN P_ID_USUARIO INT,
    IN P_ACCION VARCHAR(255),
    IN P_REPUESTO VARCHAR(100),
    IN P_COSTO DECIMAL(10,2),
    IN P_TIEMPO INT,
    IN P_ESTADO VARCHAR(20),
    IN P_RUTA VARCHAR(255)
)
proc_label: BEGIN
    DECLARE V_ESTADO_ASIGNACION VARCHAR(20);

    -- 1. Validación de existencia de asignación
    IF NOT EXISTS (SELECT 1 FROM ASIGNACIONES_RECLAMOS WHERE ID_ASIGNACION = P_ID_ASIGNACION) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: ASIGNACIÓN NO EXISTE.';
        LEAVE proc_label;
    END IF;

    -- 2. Validación de estado de reparación
    SELECT ESTADO_ASIGNACION INTO V_ESTADO_ASIGNACION 
    FROM ASIGNACIONES_RECLAMOS WHERE ID_ASIGNACION = P_ID_ASIGNACION;

    IF V_ESTADO_ASIGNACION = 'COMPLETADO' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: REPARACIÓN YA FINALIZADA.';
        LEAVE proc_label;
    END IF;

    -- 3. Inserción con todos los campos nuevos
    INSERT INTO DETALLE_REPARACIONES (
        ID_ASIGNACION, ID_USUARIO, ACCION_REALIZADA, REPUESTO_UTILIZADO, 
        COSTO_REPUESTO, TIEMPO_EMPLEADO_MIN, ESTADO_AVANCE, RUTA_EVIDENCIA
    )
    VALUES (
        P_ID_ASIGNACION, P_ID_USUARIO, P_ACCION, P_REPUESTO, 
        P_COSTO, P_TIEMPO, P_ESTADO, P_RUTA
    );
    
    SELECT 'EXITO: AVANCE Y EVIDENCIA REGISTRADOS.' AS MENSAJE;
END;

DELIMITER ;