DELIMITER //
DROP PROCEDURE IF EXISTS SP_GET_USUARIO_LOGIN //
CREATE PROCEDURE SP_GET_USUARIO_LOGIN(
    IN P_USUARIO VARCHAR(50)
)
BEGIN
    SELECT U.ID_USUARIO, U.CONTRASENA, R.NOMBRE_ROL 
    FROM USUARIOS U
    INNER JOIN ROLES R ON U.ID_ROL = R.ID_ROL
    WHERE U.USUARIO = P_USUARIO 
      AND U.ESTADO = 'ACTIVO';
END //
DELIMITER ;
