CREATE TABLE METODOS_PAGO (
    ID_METODO_PAGO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY (ID_METODO_PAGO),
    CONSTRAINT CK_METODO_NOMBRE CHECK (CHAR_LENGTH(TRIM(NOMBRE)) > 0)
) ENGINE = InnoDB;
----------------------------------------------------------------------------------------------------
-----------------------------------------[Store procedure}------------------------------------------
----------------------------------------------------------------------------------------------------


-- 1. INSERTAR 
DELIMITER //
DROP PROCEDURE IF EXISTS SP_INSERTAR_METODO_PAGO;
CREATE PROCEDURE SP_INSERTAR_METODO_PAGO(
    IN P_NOMBRE VARCHAR(50) 
)
proc_label: BEGIN
    DECLARE v_nombre_limpio VARCHAR(50);

    -- 0. LIMPIEZA PROFUNDA
    SET v_nombre_limpio = REGEXP_REPLACE(TRIM(P_NOMBRE), '[[:space:]]+', ' ');

    -- 1. VALIDACIÓN: NOMBRE OBLIGATORIO
    IF v_nombre_limpio = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL NOMBRE DEL MÉTODO DE PAGO ES OBLIGATORIO.';
        LEAVE proc_label;
    END IF;

    -- 2. VALIDACIÓN: DUPLICADOS
    IF EXISTS (SELECT 1 FROM METODOS_PAGO WHERE NOMBRE = v_nombre_limpio) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: ESTE MÉTODO DE PAGO YA EXISTE.';
        LEAVE proc_label;
    END IF;

    -- 3. INSERCIÓN FINAL
    INSERT INTO METODOS_PAGO (NOMBRE) 
    VALUES (v_nombre_limpio);

    -- 4. MENSAJE ESTANDARIZADO PARA C++
    SELECT CONCAT('EXITO: MÉTODO DE PAGO "', v_nombre_limpio, '" INSERTADO. ID: ', LAST_INSERT_ID()) AS MENSAJE;
END ;
DELIMITER ;

-- 2. ACTUALIZAR 
DELIMITER //
DROP PROCEDURE IF EXISTS SP_ACTUALIZAR_METODO_PAGO;
CREATE PROCEDURE SP_ACTUALIZAR_METODO_PAGO( 
    IN P_ID_METODO INT,
    IN P_NOMBRE    VARCHAR(50)
)
proc_label: BEGIN
    DECLARE v_nombre_limpio VARCHAR(50);

    IF NOT EXISTS (SELECT 1 FROM METODOS_PAGO WHERE ID_METODO_PAGO = P_ID_METODO) THEN 
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL MÉTODO DE PAGO NO EXISTE.';
        LEAVE proc_label;
    END IF;

    IF P_NOMBRE IS NOT NULL THEN
        SET v_nombre_limpio = REGEXP_REPLACE(TRIM(P_NOMBRE), '[[:space:]]+', ' ');
        IF v_nombre_limpio = '' THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL NOMBRE NO PUEDE ESTAR VACÍO.';
            LEAVE proc_label;
        ELSEIF EXISTS (SELECT 1 FROM METODOS_PAGO WHERE NOMBRE = v_nombre_limpio AND ID_METODO_PAGO <> P_ID_METODO) THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: ESTE MÉTODO YA EXISTE.';
            LEAVE proc_label;
        END IF;
    END IF;

    UPDATE METODOS_PAGO SET NOMBRE = COALESCE(v_nombre_limpio, NOMBRE) WHERE ID_METODO_PAGO = P_ID_METODO;

    SELECT CONCAT('EXITO: MÉTODO DE PAGO ID ', P_ID_METODO, ' ACTUALIZADO.') AS MENSAJE;
END ;
DELIMITER ;

--LISTAR 
DELIMITER //
DROP PROCEDURE IF EXISTS SP_LISTAR_METODOS_PAGO;
CREATE PROCEDURE SP_LISTAR_METODOS_PAGO()
BEGIN
    SELECT ID_METODO_PAGO, NOMBRE FROM METODOS_PAGO ORDER BY NOMBRE ASC;
END ;
DELIMITER ;

--BUSCAR
DELIMITER //
DROP PROCEDURE IF EXISTS  SP_BUSCAR_METODOS_PAGO ;

CREATE PROCEDURE SP_BUSCAR_METODOS_PAGO(
    IN P_BUSQUEDA VARCHAR(50)
)
BEGIN
    SELECT ID_METODO_PAGO, NOMBRE 
    FROM METODOS_PAGO 
    WHERE (P_BUSQUEDA IS NULL OR P_BUSQUEDA = '') 
       OR (NOMBRE LIKE CONCAT('%', P_BUSQUEDA, '%'))
    ORDER BY ID_METODO_PAGO ASC; -- <-- CAMBIADO AQUÍ (Ordena 1, 2, 3...)
END ;


DELIMITER ;



DELIMITER //

CREATE PROCEDURE SP_TOGGLE_ESTADO_METODO_PAGO(
    IN P_ID_METODO INT
)
proc_label: BEGIN
    -- 1. Validamos existencia del método de pago
    IF NOT EXISTS (SELECT 1 FROM METODOS_PAGO WHERE ID_METODO_PAGO = P_ID_METODO) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: MÉTODO DE PAGO NO ENCONTRADO.';
        LEAVE proc_label;
    END IF;

    -- 2. Realizamos el cambio de estado (Toggle)
    -- Si está ACTIVO pasa a INACTIVO, y viceversa.
    UPDATE METODOS_PAGO
    SET ESTADO = IF(ESTADO = 'ACTIVO', 'INACTIVO', 'ACTIVO')
    WHERE ID_METODO_PAGO = P_ID_METODO;

    -- 3. Retornamos el mensaje con los datos actualizados para la función Recogermensaje
    SELECT CONCAT(
        'EXITO: MÉTODO "', NOMBRE, '" (ID: ', ID_METODO_PAGO, 
        ') HA SIDO ', ESTADO, '.'
    ) AS MENSAJE
    FROM METODOS_PAGO
    WHERE ID_METODO_PAGO = P_ID_METODO;

END ;

DELIMITER ;

CALL `4_SP_INSERTAR_METODO_PAGO` ('EFECTIVO');
CALL `4_SP_INSERTAR_METODO_PAGO` ('TARJETA');
CALL `4_SP_INSERTAR_METODO_PAGO` ('TRANSFERENCIA');
CALL `4_SP_INSERTAR_METODO_PAGO` ('DEPOSITO');