CREATE TABLE AUDITORIA_SISTEMA (
    ID_AUDITORIA INT NOT NULL AUTO_INCREMENT,
    TABLA_AFECTADA VARCHAR(50) NOT NULL,
    ID_REGISTRO_AFECTADO INT NOT NULL,
    ACCION ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
    USUARIO_SISTEMA VARCHAR(50) NOT NULL, -- El usuario de la DB o del App
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VALOR_ANTERIOR TEXT, -- Datos antes del cambio (en formato JSON o String)
    VALOR_NUEVO TEXT, -- Datos después del cambio
    PRIMARY KEY (ID_AUDITORIA)
) ENGINE = InnoDB;

-- Para buscar qué pasó en una fecha específica
CREATE INDEX IX_AUDITORIA_FECHA ON AUDITORIA_SISTEMA (FECHA_HORA);

-- Para rastrear todo lo que se le ha hecho a una tabla (ej: 'VENTAS')
CREATE INDEX IX_AUDITORIA_TABLA ON AUDITORIA_SISTEMA (TABLA_AFECTADA);

----------------------------------------------------------------------------------------------------
-----------------------------------------[Store procedure}------------------------------------------
----------------------------------------------------------------------------------------------------

--LISTAR
DELIMITER //
DROP PROCEDURE IF EXISTS SP_LISTAR_AUDITORIA_GENERAL //
CREATE PROCEDURE 6_SP_LISTAR_AUDITORIA_GENERAL(
    IN P_TABLA VARCHAR(50),
    IN P_FECHA_INICIO DATE,
    IN P_FECHA_FIN DATE
)
BEGIN
    SELECT * FROM AUDITORIA_SISTEMA
    WHERE (P_TABLA IS NULL OR P_TABLA = '' OR TABLA_AFECTADA = P_TABLA)
      AND (DATE(FECHA_HORA) BETWEEN IFNULL(P_FECHA_INICIO, '1900-01-01') AND IFNULL(P_FECHA_FIN, CURDATE()))
    ORDER BY FECHA_HORA DESC;
END ;
DELIMITER ;

--CONSULTAR

DELIMITER //

DROP PROCEDURE IF EXISTS SP_CONSULTAR_HISTORIAL_REGISTRO //
CREATE PROCEDURE 6_SP_CONSULTAR_HISTORIAL_REGISTRO(
    IN P_TABLA VARCHAR(50),
    IN P_ID_REGISTRO INT
)
BEGIN
    SELECT ID_AUDITORIA, ACCION, USUARIO_SISTEMA, FECHA_HORA, VALOR_ANTERIOR, VALOR_NUEVO
    FROM AUDITORIA_SISTEMA
    WHERE TABLA_AFECTADA = P_TABLA 
      AND ID_REGISTRO_AFECTADO = P_ID_REGISTRO
    ORDER BY FECHA_HORA DESC;
END ;
DELIMITER ;

--LIMPIAR MANTEMINIENTO 

DELIMITER //

DROP PROCEDURE IF EXISTS SP_LIMPIAR_AUDITORIA //
CREATE PROCEDURE 6_SP_LIMPIAR_AUDITORIA(
    IN P_DIAS_ANTIGUEDAD INT
)
BEGIN
    DELETE FROM AUDITORIA_SISTEMA 
    WHERE FECHA_HORA < DATE_SUB(NOW(), INTERVAL P_DIAS_ANTIGUEDAD DAY);
    
    SELECT CONCAT('LIMPIEZA COMPLETADA: SE HAN ELIMINADO REGISTROS CON MÁS DE ', P_DIAS_ANTIGUEDAD, ' DÍAS.') AS MENSAJE;
END ;

DELIMITER ;



----------------------------------------------------------------------------------------------------
-----------------------------------------[TRIGERR}--------------------------------------------------
----------------------------------------------------------------------------------------------------

DELIMITER //

-- TRIGGER PARA AUDITAR INSERT
DROP TRIGGER IF EXISTS TR_AUDIT_PROVEEDORES_INSERT //
CREATE TRIGGER TR_AUDIT_PROVEEDORES_INSERT
AFTER INSERT ON PROVEEDORES
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_SISTEMA (TABLA_AFECTADA, ID_REGISTRO_AFECTADO, ACCION, USUARIO_SISTEMA, VALOR_NUEVO)
    VALUES ('PROVEEDORES', NEW.ID_PROVEEDOR, 'INSERT', USER(), 
            CONCAT('Nombre: ', NEW.NOMBRE, ', Tel: ', NEW.TELEFONO, ', Email: ', NEW.EMAIL));
END ;

-- TRIGGER PARA AUDITAR UPDATE
DROP TRIGGER IF EXISTS TR_AUDIT_PROVEEDORES_UPDATE //
CREATE TRIGGER TR_AUDIT_PROVEEDORES_UPDATE
AFTER UPDATE ON PROVEEDORES
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_SISTEMA (TABLA_AFECTADA, ID_REGISTRO_AFECTADO, ACCION, USUARIO_SISTEMA, VALOR_ANTERIOR, VALOR_NUEVO)
    VALUES ('PROVEEDORES', OLD.ID_PROVEEDOR, 'UPDATE', USER(), 
            CONCAT('Nombre: ', OLD.NOMBRE, ', Tel: ', OLD.TELEFONO, ', Email: ', OLD.EMAIL),
            CONCAT('Nombre: ', NEW.NOMBRE, ', Tel: ', NEW.TELEFONO, ', Email: ', NEW.EMAIL));
END ;

DELIMITER ;




DELIMITER //



DELIMITER //
DROP TRIGGER IF EXISTS TR_AUDITORIA_PRODUCTOS_UPDATE ;
CREATE TRIGGER TR_AUDITORIA_PRODUCTOS_UPDATE
AFTER UPDATE ON PRODUCTOS
FOR EACH ROW
BEGIN
    -- Auditamos el PRECIO_VENTA
    IF OLD.PRECIO_VENTA <> NEW.PRECIO_VENTA THEN
        INSERT INTO AUDITORIA_SISTEMA (
            TABLA_AFECTADA, 
            ID_REGISTRO_AFECTADO, 
            ACCION, 
            USUARIO_SISTEMA, 
            VALOR_ANTERIOR, 
            VALOR_NUEVO
        ) VALUES (
            'PRODUCTOS', 
            NEW.ID_PRODUCTO, 
            'UPDATE', 
            USER(),
            CONCAT('Precio venta anterior: ', OLD.PRECIO_VENTA), 
            CONCAT('Precio venta nuevo: ', NEW.PRECIO_VENTA)
        );
    END IF;
END ;
DELIMITER ;