CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    CEDULA VARCHAR (20) NOT NULL,
    CARGO VARCHAR(50) NOT NULL,
    SALARIO DECIMAL(10, 2) NOT NULL CHECK (SALARIO > 0),
    TELEFONO VARCHAR(20) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    FECHA_INGRESO DATE NOT NULL,
    FECHA_DESPIDO DATE NULL,
    ESTADO ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT CK_EMPLEADO_NOMBRE CHECK (CHAR_LENGTH(TRIM(NOMBRE)) > 0)
) ENGINE = InnoDB;

 
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------[Store procedure}-------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------      
--1. INSERTAR EMPLEADOS 
DELIMITER //

DROP PROCEDURE IF EXISTS SP_INSERTAR_EMPLEADO ;
CREATE OR REPLACE PROCEDURE SP_INSERTAR_EMPLEADO(
    IN P_NOMBRE    VARCHAR(100),
    IN P_CEDULA    VARCHAR(15),
    IN P_CARGO     VARCHAR(50),
    IN P_SALARIO   DECIMAL(10, 2),
    IN P_TELEFONO  VARCHAR(20),
    IN P_EMAIL     VARCHAR(100)
)
proc_label: BEGIN 
    DECLARE v_nombre_limpio   VARCHAR(100);
    DECLARE v_cedula_limpia   VARCHAR(15);
    DECLARE v_telefono_limpio VARCHAR(20);
    DECLARE v_email_limpio    VARCHAR(100);

    -- 0. LIMPIEZA
    SET v_nombre_limpio   = REGEXP_REPLACE(TRIM(P_NOMBRE), '[[:space:]]+', ' ');
    SET v_cedula_limpia   = REGEXP_REPLACE(P_CEDULA, '[[:space:]\-]', '');
    SET v_telefono_limpio = REGEXP_REPLACE(P_TELEFONO, '[[:space:]()\-]', '');
    SET v_email_limpio    = LOWER(REPLACE(P_EMAIL, ' ', ''));
    

    -- 1. VALIDACIÓN: DATOS OBLIGATORIOS
    IF v_nombre_limpio = '' OR v_cedula_limpia = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: NOMBRE Y CÉDULA SON OBLIGATORIOS.';
        LEAVE proc_label;
    END IF;

    -- 2. VALIDACIÓN: DUPLICADOS
    IF EXISTS (SELECT 1 FROM EMPLEADOS WHERE CEDULA = v_cedula_limpia) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: YA EXISTE UN EMPLEADO CON ESTA CÉDULA.';
        LEAVE proc_label;
    END IF;

    IF EXISTS (SELECT 1 FROM EMPLEADOS WHERE EMAIL = v_email_limpio) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: ESTE EMAIL YA ESTÁ REGISTRADO.';
        LEAVE proc_label;
    END IF;

    IF EXISTS (SELECT 1 FROM EMPLEADOS WHERE TELEFONO = v_telefono_limpio) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: ESTE TELÉFONO YA ESTÁ REGISTRADO.';
        LEAVE proc_label;
    END IF;

    -- 3. VALIDACIÓN: SALARIO
    IF P_SALARIO <= 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL SALARIO DEBE SER MAYOR A CERO.';
        LEAVE proc_label;
    END IF;

    -- 4. INSERCIÓN FINAL
 INSERT INTO EMPLEADOS (NOMBRE, CEDULA, CARGO, SALARIO, TELEFONO, EMAIL, FECHA_INGRESO)
VALUES (v_nombre_limpio, v_cedula_limpia, P_CARGO, P_SALARIO, v_telefono_limpio, v_email_limpio, CURDATE());

    SELECT CONCAT('EXITO: EMPLEADO "', v_nombre_limpio, '" INSERTADO. ID: ', LAST_INSERT_ID()) AS MENSAJE;

END;

DELIMITER ;

DELIMITER ;
    


--2. ACTUALIZAR EMPLEADO 

DELIMITER //

DROP PROCEDURE IF EXISTS SP_ACTUALIZAR_EMPLEADO ;

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_EMPLEADO(
    IN P_ID_EMPLEADO INT,
    IN P_NOMBRE      VARCHAR(100),
    IN P_CEDULA      VARCHAR(20),  -- Nuevo parámetro
    IN P_CARGO       VARCHAR(50),
    IN P_SALARIO     DECIMAL(10, 2),
    IN P_TELEFONO    VARCHAR(20),
    IN P_EMAIL       VARCHAR(100)
)
proc_label: BEGIN
    -- Variables para limpieza
    DECLARE v_nombre_limpio    VARCHAR(100);
    DECLARE v_cedula_limpia    VARCHAR(20);
    DECLARE v_cargo_limpio     VARCHAR(50);
    DECLARE v_telefono_limpio  VARCHAR(20);
    DECLARE v_email_limpio     VARCHAR(100);

    -- 1. VALIDAR EXISTENCIA
    IF NOT EXISTS (SELECT 1 FROM EMPLEADOS WHERE ID_EMPLEADO = P_ID_EMPLEADO) THEN 
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL EMPLEADO NO EXISTE.';
        LEAVE proc_label;
    END IF;

    -- 2. LIMPIEZA Y VALIDACIONES
    IF P_NOMBRE IS NOT NULL THEN
        SET v_nombre_limpio = REGEXP_REPLACE(TRIM(P_NOMBRE), '[[:space:]]+', ' ');
    END IF;

    -- Validación de Cédula
    IF P_CEDULA IS NOT NULL THEN
        SET v_cedula_limpia = REGEXP_REPLACE(P_CEDULA, '[[:space:]\-]', '');
        IF v_cedula_limpia = '' THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: LA CÉDULA NO PUEDE ESTAR VACÍA.';
            LEAVE proc_label;
        ELSEIF EXISTS (SELECT 1 FROM EMPLEADOS WHERE CEDULA = v_cedula_limpia AND ID_EMPLEADO <> P_ID_EMPLEADO) THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: LA CÉDULA YA PERTENECE A OTRO EMPLEADO.';
            LEAVE proc_label;
        END IF;
    END IF;

    IF P_CARGO IS NOT NULL THEN
        SET v_cargo_limpio = REGEXP_REPLACE(TRIM(P_CARGO), '[[:space:]]+', ' ');
    END IF;

    IF P_TELEFONO IS NOT NULL THEN
        SET v_telefono_limpio = REGEXP_REPLACE(P_TELEFONO, '[[:space:]()\-]', '');
        IF EXISTS (SELECT 1 FROM EMPLEADOS WHERE TELEFONO = v_telefono_limpio AND ID_EMPLEADO <> P_ID_EMPLEADO) THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL TELÉFONO YA PERTENECE A OTRO EMPLEADO.';
            LEAVE proc_label;
        END IF;
    END IF;

    IF P_EMAIL IS NOT NULL THEN
        SET v_email_limpio = LOWER(REPLACE(P_EMAIL, ' ', ''));
        IF EXISTS (SELECT 1 FROM EMPLEADOS WHERE EMAIL = v_email_limpio AND ID_EMPLEADO <> P_ID_EMPLEADO) THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL EMAIL YA PERTENECE A OTRO EMPLEADO.';
            LEAVE proc_label;
        END IF;
    END IF;

    -- 3. ACTUALIZACIÓN DINÁMICA 
    UPDATE EMPLEADOS 
    SET 
        NOMBRE   = COALESCE(v_nombre_limpio, NOMBRE),
        CEDULA   = COALESCE(v_cedula_limpia, CEDULA),
        CARGO    = COALESCE(v_cargo_limpio, CARGO),
        SALARIO  = COALESCE(IF(P_SALARIO > 0, P_SALARIO, NULL), SALARIO),
        TELEFONO = COALESCE(v_telefono_limpio, TELEFONO),
        EMAIL    = COALESCE(v_email_limpio, EMAIL)
    WHERE ID_EMPLEADO = P_ID_EMPLEADO;

    -- 4. MENSAJE DE ÉXITO
    SELECT CONCAT('EXITO: EMPLEADO "', NOMBRE, '" ACTUALIZADO CON ÉXITO.') AS MENSAJE
    FROM EMPLEADOS WHERE ID_EMPLEADO = P_ID_EMPLEADO;

END ;
DELIMITER ;

--3. DESPECIR EMPLEADO
DELIMITER //
DROP PROCEDURE IF EXISTS SP_DESPEDIR_EMPLEADO;
CREATE PROCEDURE SP_DESPEDIR_EMPLEADO(
    IN P_ID_EMPLEADO   INT,
    IN P_FECHA_DESPIDO DATE
)
proc_label: BEGIN

    -- 1. VALIDAR QUE EL EMPLEADO EXISTE
    IF NOT EXISTS (SELECT 1 FROM EMPLEADOS WHERE ID_EMPLEADO = P_ID_EMPLEADO) THEN 
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL EMPLEADO NO EXISTE EN LA BASE DE DATOS.';
        LEAVE proc_label;
    END IF;

    -- 2. VALIDAR QUE NO ESTÉ YA INACTIVO (Para evitar doble despido)
    IF EXISTS (SELECT 1 FROM EMPLEADOS WHERE ID_EMPLEADO = P_ID_EMPLEADO AND ESTADO = 'INACTIVO') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'AVISO: ESTE EMPLEADO YA CONSTA COMO INACTIVO.';
        LEAVE proc_label;
    END IF;

    -- 3. ASIGNAR FECHA AUTOMÁTICA SI VIENE NULA
    -- Si desde tu app no mandas fecha, el sistema asume que es hoy
    IF P_FECHA_DESPIDO IS NULL THEN
        SET P_FECHA_DESPIDO = CURRENT_DATE;
    END IF;

    
IF P_FECHA_DESPIDO > CURRENT_DATE THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: LA FECHA DE DESPIDO NO PUEDE SER FUTURA.';
    LEAVE proc_label;
END IF;

    -- 4. ACTUALIZACIÓN DE ESTADO Y SALIDA 
    UPDATE EMPLEADOS 
    SET 
        ESTADO = 'INACTIVO',
        FECHA_DESPIDO = P_FECHA_DESPIDO
    WHERE ID_EMPLEADO = P_ID_EMPLEADO;

    -- 5. RESPUESTA
    SELECT CONCAT('EXITO: EL EMPLEADO ID ', P_ID_EMPLEADO, ' HA SIDO DADO DE BAJA.') AS MENSAJE;

END ;
DELIMITER ;

--4. REACTIVAR ENPLEADO 
DELIMITER //
DROP PROCEDURE IF EXISTS  SP_REACTIVAR_EMPLEADO;
CREATE PROCEDURE SP_REACTIVAR_EMPLEADO(
    IN P_ID_EMPLEADO INT,
    IN P_NUEVO_SALARIO DECIMAL(10,2)
)
proc_label: BEGIN

    -- 1. VALIDAR QUE EL ID EXISTE
    IF NOT EXISTS (SELECT 1 FROM EMPLEADOS WHERE ID_EMPLEADO = P_ID_EMPLEADO) THEN 
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL ID DE EMPLEADO NO EXISTE.';
        LEAVE proc_label;
    END IF;

    -- 2. VALIDAR QUE EL EMPLEADO ESTÉ INACTIVO
    -- No tiene sentido reactivar a alguien que ya está trabajando
    IF EXISTS (SELECT 1 FROM EMPLEADOS WHERE ID_EMPLEADO = P_ID_EMPLEADO AND ESTADO = 'ACTIVO') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'AVISO: EL EMPLEADO YA SE ENCUENTRA ACTIVO.';
        LEAVE proc_label;
    END IF;

    -- 3. VALIDAR EL NUEVO SALARIO (Solo si no es NULL)
    IF P_NUEVO_SALARIO IS NOT NULL AND P_NUEVO_SALARIO <= 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL NUEVO SALARIO DEBE SER MAYOR A CERO.';
        LEAVE proc_label;
    END IF;

    -- 4. ACTUALIZACIÓN DE REINGRESO
    UPDATE EMPLEADOS 
    SET 
        ESTADO = 'ACTIVO',
        FECHA_DESPIDO = NULL,
        FECHA_INGRESO = CURRENT_DATE, -- Se actualiza a la fecha actual de reingreso
        SALARIO = COALESCE(P_NUEVO_SALARIO, SALARIO)
    WHERE ID_EMPLEADO = P_ID_EMPLEADO;
    
    -- 5. RESPUESTA
    SELECT CONCAT('EXITO: EMPLEADO ID ', P_ID_EMPLEADO, ' REINGRESADO CORRECTAMENTE.') AS MENSAJE;

END ;

DELIMITER ;

---4. REPORTE DE NOMINA

DELIMITER //
DROP PROCEDURE IF EXISTS SP_REPORTE_NOMINA_TOTAL;
CREATE PROCEDURE SP_REPORTE_NOMINA_TOTAL()
proc_label: BEGIN

    -- 1. VERIFICAR SI HAY EMPLEADOS ACTIVOS
    -- Si no hay nadie, devolvemos un mensaje claro en lugar de una tabla con NULLs
    IF NOT EXISTS (SELECT 1 FROM EMPLEADOS WHERE ESTADO = 'ACTIVO') THEN
        SELECT 'AVISO: NO HAY EMPLEADOS ACTIVOS PARA GENERAR NÓMINA.' AS MENSAJE;
        LEAVE proc_label;
    END IF;

    -- 2. CONSULTA DE NÓMINA CON FORMATEO
    -- Usamos IFNULL para asegurar que los cálculos siempre devuelvan 0 en lugar de NULL
    SELECT 
        COUNT(*) AS TOTAL_EMPLEADOS,
        IFNULL(SUM(SALARIO), 0) AS GASTO_MENSUAL_NOMINA,
        IFNULL(MIN(SALARIO), 0) AS SUELDO_MINIMO,
        IFNULL(MAX(SALARIO), 0) AS SUELDO_MAXIMO,
        IFNULL(AVG(SALARIO), 0) AS SUELDO_PROMEDIO -- Añadimos el promedio para mejor reporte
    FROM EMPLEADOS
    WHERE ESTADO = 'ACTIVO';


    -- Agrega esto al final del SP o crea un nuevo SP llamado 8_SP_REPORTE_NOMINA_POR_CARGO
SELECT 
    CARGO,
    COUNT(*) AS EMPLEADOS_POR_CARGO,
    SUM(SALARIO) AS TOTAL_POR_CARGO
FROM EMPLEADOS
WHERE ESTADO = 'ACTIVO'
GROUP BY CARGO;

END ;
DELIMITER ;

--5. BUSCAR ENPLEADOS DINAMICA

DELIMITER //
DROP PROCEDURE IF EXISTS  SP_CONSULTAR_EMPLEADOS ;
CREATE PROCEDURE SP_CONSULTAR_EMPLEADOS(
    IN P_ID_EMPLEADO   INT,
    IN P_FILTRO_NOMBRE VARCHAR(100)
)
BEGIN
    -- La lógica funciona así:
    -- 1. Si mandas el ID, prioriza la búsqueda por ese ID.
    -- 2. Si el ID es NULL, busca por nombre (coincidencia parcial).
    -- 3. Si ambos son NULL, trae la lista completa.

    SELECT 
        ID_EMPLEADO,
        CEDULA,
        NOMBRE,
        CARGO,
        SALARIO,
        TELEFONO,
        EMAIL,
        FECHA_INGRESO,
        FECHA_DESPIDO,
        ESTADO
    FROM EMPLEADOS
    WHERE 
        (P_ID_EMPLEADO IS NULL OR ID_EMPLEADO = P_ID_EMPLEADO)
        AND 
        (P_FILTRO_NOMBRE IS NULL OR TRIM(P_FILTRO_NOMBRE) = '' OR NOMBRE LIKE CONCAT('%', P_FILTRO_NOMBRE, '%'))
    ORDER BY ID_EMPLEADO DESC;

END ;

DELIMITER ;


--- 6. AUMENTO POR CARGO
DELIMITER //

DROP PROCEDURE IF EXISTS SP_AUMENTO_POR_CARGO ;
CREATE PROCEDURE SP_AUMENTO_POR_CARGO(
    IN P_ID_EMPLEADO   INT,
    IN P_CARGO         VARCHAR(50),
    IN P_PORCENTAJE    DECIMAL(5, 2)
)
proc_label: BEGIN
    DECLARE v_registros_afectados INT DEFAULT 0;

    -- 1. TRANSACCIÓN: Asegura que si algo falla, no se aplique el aumento a medias
    START TRANSACTION;

    -- 2. VALIDACIONES (Iguales a las tuyas, que están bien)
    IF (P_ID_EMPLEADO IS NULL) AND (P_CARGO IS NULL OR TRIM(P_CARGO) = '') THEN
        ROLLBACK;
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: ESPECIFIQUE ID O CARGO.';
        LEAVE proc_label;
    END IF; 

    -- 3. CÁLCULO Y ACTUALIZACIÓN CON REDONDEO
    -- Usamos ROUND para evitar centavos infinitos o errores de precisión decimal
    UPDATE EMPLEADOS 
    SET SALARIO = ROUND(SALARIO + (SALARIO * (P_PORCENTAJE / 100)), 2)
    WHERE (P_ID_EMPLEADO IS NULL OR ID_EMPLEADO = P_ID_EMPLEADO)
      AND (P_CARGO IS NULL OR CARGO = P_CARGO)
      AND ESTADO = 'ACTIVO';
    
    SET v_registros_afectados = ROW_COUNT();

    -- 4. VALIDACIÓN DE ÉXITO
    IF v_registros_afectados = 0 THEN
        ROLLBACK;
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: NO SE ENCONTRARON EMPLEADOS ACTIVOS PARA EL FILTRO DADO.';
    ELSE
        -- 5. COMMIT: Guarda los cambios permanentemente
        COMMIT;
        SELECT CONCAT('EXITO: SE APLICÓ EL AUMENTO A ', v_registros_afectados, ' EMPLEADO(S).') AS MENSAJE;
    END IF;

END ;

DELIMITER ;

--- 7. ANIVERSARIO DE EMPLEADO EN LA EMPRESA 
DELIMITER //
drop PROCEDURE if EXISTS SP_ANIVERSARIOS_MES;
CREATE PROCEDURE SP_ANIVERSARIOS_MES()
proc_label: BEGIN

    -- 1. VALIDAR SI EXISTEN EMPLEADOS ACTIVOS EN GENERAL
    IF NOT EXISTS (SELECT 1 FROM EMPLEADOS WHERE ESTADO = 'ACTIVO') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: NO HAY EMPLEADOS ACTIVOS EN LA BASE DE DATOS.';
        LEAVE proc_label;
    END IF;

    -- 2. VERIFICAR SI HAY ALGUIEN DE ANIVERSARIO ESTE MES
    -- Esto evita que el DataReader en C++ se quede esperando filas que no existen
    IF NOT EXISTS (
        SELECT 1 FROM EMPLEADOS 
        WHERE MONTH(FECHA_INGRESO) = MONTH(CURRENT_DATE) 
          AND ESTADO = 'ACTIVO'
    ) THEN
        SELECT 'INFORMATIVO: NO HAY ANIVERSARIOS LABORALES EN EL MES ACTUAL.' AS MENSAJE;
        LEAVE proc_label;
    END IF;

    -- 3. CONSULTA FINAL
    SELECT 
        ID_EMPLEADO,
        NOMBRE,
        CARGO,
        FECHA_INGRESO,
        TIMESTAMPDIFF(YEAR, FECHA_INGRESO, CURRENT_DATE) AS ANOS_EN_EMPRESA
    FROM EMPLEADOS
    WHERE MONTH(FECHA_INGRESO) = MONTH(CURRENT_DATE) 
      AND ESTADO = 'ACTIVO'
    ORDER BY DAY(FECHA_INGRESO) ASC; -- Ordenados por el día que cumplen

END ;

DELIMITER ;


---8. BUSCAR ENPLEADO
DELIMITER //
DROP PROCEDURE IF EXISTS SP_BUSQUEDA_RAPIDA_EMPLEADOS;

CREATE PROCEDURE SP_BUSQUEDA_RAPIDA_EMPLEADOS(
    IN P_TERMINO VARCHAR(100)
)
proc_label: BEGIN

    -- 1. VALIDAR QUE EL TERMINO DE BUSQUEDA NO ESTE VACIO
    IF P_TERMINO IS NULL OR TRIM(P_TERMINO) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: DEBE INGRESAR UN DATO PARA BUSCAR.';
        LEAVE proc_label;
    END IF;

    -- 2. BUSQUEDA MULTI-CRITERIO
    -- Buscamos coincidencias en ID, Cedula, Nombre o Cargo
    SELECT 
        ID_EMPLEADO,
        CEDULA,
        NOMBRE,
        CARGO,
        ESTADO
    FROM EMPLEADOS
    WHERE (
        ID_EMPLEADO = P_TERMINO -- Si es un número exacto
        OR CEDULA LIKE CONCAT('%', P_TERMINO, '%')
        OR NOMBRE LIKE CONCAT('%', P_TERMINO, '%')
        OR CARGO  LIKE CONCAT('%', P_TERMINO, '%')
    )
    ORDER BY ESTADO ASC, NOMBRE ASC; -- Muestra primero los activos y luego por orden alfabetico

    -- 3. VALIDAR SI NO SE ENCONTRARON RESULTADOS
    -- Nota: En C++, si el ResultSet está vacío, sabrás que no hubo coincidencias.

END ;

DELIMITER ;


---9. VOLANTE DE PAGO
DELIMITER //
drop PROCEDURE IF EXISTS  SP_GENERAR_RECIBO_EMPLEADO ;
CREATE PROCEDURE SP_GENERAR_RECIBO_EMPLEADO  (
    IN P_ID_EMPLEADO INT
)
proc_label: BEGIN

    -- 1. VALIDAR QUE EL ID NO SEA NULO
    IF P_ID_EMPLEADO IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: DEBE PROPORCIONAR UN ID DE EMPLEADO.';
        LEAVE proc_label;
    END IF;

    -- 2. VALIDAR QUE EL EMPLEADO EXISTA Y ESTÉ ACTIVO
    IF NOT EXISTS (SELECT 1 FROM EMPLEADOS WHERE ID_EMPLEADO = P_ID_EMPLEADO AND ESTADO = 'ACTIVO') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL EMPLEADO NO EXISTE O NO SE ENCUENTRA ACTIVO.';
        LEAVE proc_label;
    END IF;

    -- 3. GENERAR EL RECIBO DETALLADO
    SELECT 
        'BALBU_TECH - SOLUCIONES TECNOLÓGICAS' AS EMPRESA,
        ID_EMPLEADO,
        NOMBRE,
        CEDULA,
        CARGO,
        SALARIO AS SUELDO_BRUTO,
        -- Cálculo de Seguridad Social (SFS 3.04%, AFP 2.87% - Valores típicos en RD)
        ROUND(SALARIO * 0.0304, 2) AS DESCUENTO_SFS,
        ROUND(SALARIO * 0.0287, 2) AS DESCUENTO_AFP,
        -- Cálculo del Neto
        ROUND(SALARIO - (SALARIO * 0.0591), 2) AS SUELDO_NETO,
        DATE_FORMAT(CURRENT_DATE, '%d/%m/%Y') AS FECHA_EMISION
    FROM EMPLEADOS
    WHERE ID_EMPLEADO = P_ID_EMPLEADO;

END ;

DELIMITER ;


----------------------------------------------------------------------------------------------------
-----------------------------------------[TRIGERR}--------------------------------------------------
----------------------------------------------------------------------------------------------------





DELIMITER //
DROP TRIGGER IF EXISTS TRG_CARGO_UPPER;
CREATE TRIGGER TRG_CARGO_UPPER BEFORE INSERT ON EMPLEADOS
FOR EACH ROW
BEGIN
    SET NEW.CARGO = UPPER(NEW.CARGO);
END;

CREATE TRIGGER TRG_CARGO_UPPER_UPDATE BEFORE UPDATE ON EMPLEADOS
FOR EACH ROW
BEGIN
    SET NEW.CARGO = UPPER(NEW.CARGO);
END;

DELIMITER ;