CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL CHECK (PRECIO > 0),
    CODIGO VARCHAR(20) NOT NULL UNIQUE,
    ESTADO ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_MARCA INT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT UQ_PRODUCTO_NOMBRE_MARCA UNIQUE (NOMBRE, ID_MARCA),
    CONSTRAINT FK_PRODUCTO_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCAS (ID_MARCA),
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA)
) ENGINE = InnoDB;

SELECT * FROM `MARCAS`;

SELECT * from `CATEGORIAS`;

CREATE INDEX IX_PRODUCTOS_MARCA ON PRODUCTOS (ID_MARCA);

CREATE INDEX IX_PRODUCTOS_CATEGORIA ON PRODUCTOS (ID_CATEGORIA);


-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------[Store procedure}-------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------                
DESCRIBE PRODUCTOS;

--1. INSERTAR

DELIMITER //
DROP PROCEDURE IF EXISTS SP_INSERTAR_PRODUCTO ;


CREATE PROCEDURE SP_INSERTAR_PRODUCTO(
    IN P_NOMBRE      VARCHAR(100),
    IN P_DESCRIPCION VARCHAR(255),
    IN P_PRECIO      DECIMAL(10, 2),
    IN P_CODIGO      VARCHAR(20),
    IN P_ID_MARCA    INT,
    IN P_ID_CATEGORIA INT
) 
proc_label: BEGIN
    DECLARE v_nombre_limpio VARCHAR(100);
    DECLARE v_desc_limpia   VARCHAR(255);
    DECLARE v_codigo_limpio VARCHAR(20);

    -- 1. LIMPIEZA
    SET v_nombre_limpio = REGEXP_REPLACE(TRIM(P_NOMBRE), '[[:space:]]+', ' ');
    SET v_desc_limpia   = REGEXP_REPLACE(TRIM(P_DESCRIPCION), '[[:space:]]+', ' ');
    SET v_codigo_limpio = UPPER(TRIM(P_CODIGO));

    -- 2. VALIDACIONES DE INTEGRIDAD
    IF NOT EXISTS (SELECT 1 FROM MARCAS WHERE ID_MARCA = P_ID_MARCA) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: LA MARCA NO EXISTE.';
        LEAVE proc_label;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM CATEGORIAS WHERE ID_CATEGORIA = P_ID_CATEGORIA) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: LA CATEGORÍA NO EXISTE.';
        LEAVE proc_label;
    END IF;

    -- CORRECCIÓN AQUÍ: Añadimos alias 'PRODUCTOS' explícito para evitar conflictos de nombres
    IF EXISTS (SELECT 1 FROM PRODUCTOS AS Prod WHERE Prod.CODIGO = v_codigo_limpio) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL CÓDIGO YA ESTÁ REGISTRADO EN OTRO PRODUCTO.';
        LEAVE proc_label;
    END IF;

    IF P_PRECIO <= 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL PRECIO DEBE SER MAYOR A CERO.';
        LEAVE proc_label;
    END IF;

    IF LENGTH(v_desc_limpia) < 10 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: DESCRIPCIÓN DEMASIADO CORTA (MÍNIMO 10 CARACTERES).';
        LEAVE proc_label;
    END IF;

    -- 3. INSERCIÓN
    INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA)
    VALUES (v_nombre_limpio, v_desc_limpia, P_PRECIO, v_codigo_limpio, P_ID_MARCA, P_ID_CATEGORIA);

    SELECT CONCAT('EXITO: PRODUCTO "', v_nombre_limpio, '" REGISTRADO CORRECTAMENTE.') AS MENSAJE;

END ;

DELIMITER ;

DESCRIBE productos;

--2. ACTUALIZAR

DELIMITER //
 
DROP PROCEDURE IF EXISTS SP_ACTUALIZAR_PRODUCTOS ;

CREATE PROCEDURE SP_ACTUALIZAR_PRODUCTOS(
    IN P_ID_PRODUCTO  INT,
    IN P_NOMBRE       VARCHAR(100), 
    IN P_DESCRIPCION  VARCHAR(255),
    IN P_PRECIO       DECIMAL(10, 2),
    IN P_CODIGO       VARCHAR(20),
    IN P_ID_MARCA     INT,
    IN P_ID_CATEGORIA INT
)
proc_label: BEGIN
    DECLARE v_nombre_limpio VARCHAR(100); 
    DECLARE v_desc_limpia   VARCHAR(255);
    DECLARE v_codigo_limpio VARCHAR(20);

    -- 1. VALIDAR EXISTENCIA
    IF NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = P_ID_PRODUCTO) THEN 
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL PRODUCTO NO EXISTE.';
        LEAVE proc_label;
    END IF;

    -- 2. LIMPIEZA Y VALIDACIONES CONDICIONALES
    IF P_NOMBRE IS NOT NULL THEN
        SET v_nombre_limpio = REGEXP_REPLACE(TRIM(P_NOMBRE), '[[:space:]]+', ' ');
        IF v_nombre_limpio = '' THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL NOMBRE NO PUEDE ESTAR VACÍO.';
            LEAVE proc_label;
        END IF;
    END IF;

    IF P_DESCRIPCION IS NOT NULL THEN
        SET v_desc_limpia = REGEXP_REPLACE(TRIM(P_DESCRIPCION), '[[:space:]]+', ' ');
    END IF;

    IF P_CODIGO IS NOT NULL THEN
        SET v_codigo_limpio = UPPER(TRIM(P_CODIGO));
        IF EXISTS (SELECT 1 FROM PRODUCTOS WHERE CODIGO = v_codigo_limpio AND ID_PRODUCTO <> P_ID_PRODUCTO) THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: ESTE CÓDIGO YA PERTENECE A OTRO PRODUCTO.';
            LEAVE proc_label;
        END IF;
    END IF;

    -- NUEVA VALIDACIÓN: Si mandan precio, debe ser mayor que cero
    IF P_PRECIO IS NOT NULL THEN
        IF P_PRECIO <= 0 THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL PRECIO DEBE SER MAYOR A CERO.';
            LEAVE proc_label;
        END IF;
    END IF;

    -- Validar FKs si se intentan cambiar
    IF P_ID_MARCA IS NOT NULL AND NOT EXISTS (SELECT 1 FROM MARCAS WHERE ID_MARCA = P_ID_MARCA) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: LA MARCA NO EXISTE.';
        LEAVE proc_label;
    END IF;

    IF P_ID_CATEGORIA IS NOT NULL AND NOT EXISTS (SELECT 1 FROM CATEGORIAS WHERE ID_CATEGORIA = P_ID_CATEGORIA) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: LA CATEGORÍA NO EXISTE.';
        LEAVE proc_label;
    END IF;

    -- 3. ACTUALIZACIÓN DINÁMICA (Simplificada y segura)
    UPDATE PRODUCTOS 
    SET 
        NOMBRE       = COALESCE(v_nombre_limpio, NOMBRE),
        DESCRIPCION  = COALESCE(v_desc_limpia, DESCRIPCION),
        PRECIO       = COALESCE(P_PRECIO, PRECIO), -- Ya validado arriba
        CODIGO       = COALESCE(v_codigo_limpio, CODIGO),
        ID_MARCA     = COALESCE(P_ID_MARCA, ID_MARCA),
        ID_CATEGORIA = COALESCE(P_ID_CATEGORIA, ID_CATEGORIA)
    WHERE ID_PRODUCTO = P_ID_PRODUCTO;

    -- 4. MENSAJE DE RETORNO (Estilo BALBU_TECH)
    SET @mensaje_final = (SELECT CONCAT('EXITO: EL PRODUCTO "', 
                                        COALESCE(v_nombre_limpio, NOMBRE), 
                                        '" FUE ACTUALIZADO. (CÓDIGO: ', 
                                        COALESCE(v_codigo_limpio, CODIGO), 
                                        ')') 
                          FROM PRODUCTOS WHERE ID_PRODUCTO = P_ID_PRODUCTO);

    SELECT @mensaje_final AS MENSAJE;

END ;

DELIMITER ;


--3. Activar/Decastivar
DELIMITER //
DROP PROCEDURE IF EXISTS SP_TOGGLE_ESTADO_PRODUCTOS;
CREATE PROCEDURE SP_TOGGLE_ESTADO_PRODUCTOS(
    IN P_ID_PRODUCTO INT
)
proc_label: BEGIN
    -- 1. Variables para capturar la info actual
    DECLARE v_NOMBRE VARCHAR(100);
    DECLARE v_ESTADO_ACTUAL VARCHAR(20);
    DECLARE v_NUEVO_ESTADO VARCHAR(20);

  IF NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = P_ID_PRODUCTO) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: EL PRODUCTO NO EXISTE.';
    LEAVE proc_label;
END IF;

    -- 3. Obtener el nombre y el estado actual
    SELECT `NOMBRE`, `ESTADO` INTO v_NOMBRE, v_ESTADO_ACTUAL 
    FROM `PRODUCTOS` 
    WHERE `ID_PRODUCTO` = P_ID_PRODUCTO;

    -- 4. Lógica del "Interruptor" (Toggle)
    IF v_ESTADO_ACTUAL = 'ACTIVO' THEN
        SET v_NUEVO_ESTADO = 'INACTIVO';
    ELSE
        SET v_NUEVO_ESTADO = 'ACTIVO';
    END IF;

    -- 5. Aplicar el cambio en la tabla
    UPDATE `PRODUCTOS` 
    SET `ESTADO` = v_NUEVO_ESTADO 
    WHERE `ID_PRODUCTO` = P_ID_PRODUCTO;

    -- 6. Mensaje de confirmación final
    SELECT CONCAT(
        'PRODUCTO: "', v_NOMBRE, 
        '" - CAMBIO DE: ', v_ESTADO_ACTUAL, 
        ' A: ', v_NUEVO_ESTADO
    ) AS MENSAJE;

END ;
DELIMITER ;

---4. CONSULTAR PRODUCTO FILTRADO
DELIMITER //
DROP PROCEDURE IF EXISTS SP_CONSULTAR_PRODUCTOS_FILTRADO  ;


CREATE PROCEDURE SP_CONSULTAR_PRODUCTOS_FILTRADO(
    IN P_BUSQUEDA VARCHAR(100)
)
BEGIN
    SELECT 
        P.ID_PRODUCTO,
        P.CODIGO,
        P.NOMBRE,
        M.NOMBRE AS MARCA,
        C.NOMBRE AS CATEGORIA,
        P.PRECIO,
        P.ESTADO
    FROM PRODUCTOS P
    INNER JOIN MARCAS M ON P.ID_MARCA = M.ID_MARCA
    INNER JOIN CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
    WHERE (P_BUSQUEDA IS NULL OR P_BUSQUEDA = '' 
           OR P.NOMBRE LIKE CONCAT('%', P_BUSQUEDA, '%') 
           OR P.CODIGO = P_BUSQUEDA)
    ORDER BY P.ID_PRODUCTO ASC; -- <-- CAMBIADO AQUÍ (Ordena 1, 2, 3...)
END //

DELIMITER ;  

--5. consultar inventario
DELIMITER //
DROP PROCEDURE IF EXISTS SP_CONSULTAR_INVENTARIO ;
CREATE PROCEDURE SP_CONSULTAR_INVENTARIO(
    IN P_FILTRO VARCHAR(100)
)
BEGIN
    SELECT 
        P.ID_PRODUCTO, -- Agregado para consistencia visual
        P.CODIGO,
        P.NOMBRE,
        C.NOMBRE AS CATEGORIA,
        M.NOMBRE AS MARCA,
        I.STOCK_ACTUAL,
        I.STOCK_MINIMO,
        I.UBICACION,
        P.PRECIO,
        -- CONTROL DE ALERTAS CON MÚLTIPLES CONDICIONES (Else If)
        CASE 
            WHEN I.STOCK_ACTUAL = 0 THEN 'AGOTADO'
            WHEN I.STOCK_ACTUAL <= I.STOCK_MINIMO THEN 'CRÍTICO' 
            WHEN I.STOCK_ACTUAL <= (I.STOCK_MINIMO * 2) THEN 'STOCK BAJO'
            ELSE 'OK' 
        END AS ESTATUS_STOCK
    FROM PRODUCTOS P
    LEFT JOIN INVENTARIO I ON P.ID_PRODUCTO = I.ID_PRODUCTO
    LEFT JOIN CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
    LEFT JOIN MARCAS M ON P.ID_MARCA = M.ID_MARCA
    WHERE (P_FILTRO IS NULL OR P_FILTRO = '' 
           OR P.NOMBRE LIKE CONCAT('%', P_FILTRO, '%') 
           OR P.CODIGO LIKE CONCAT('%', P_FILTRO, '%')
           OR C.NOMBRE LIKE CONCAT('%', P_FILTRO, '%'))
      AND P.ESTADO = 'ACTIVO'
    ORDER BY P.ID_PRODUCTO ASC; -- Ordenado numéricamente por ID de producto
END //
DELIMITER ;
--6. REPORTE STOCK 
DELIMITER //
DROP PROCEDURE IF EXISTS SP_REPORTE_STOCK_CRITICO ;
CREATE PROCEDURE SP_REPORTE_STOCK_CRITICO()
BEGIN
    SELECT 
        P.NOMBRE,
        I.STOCK_ACTUAL,
        I.STOCK_MINIMO,
        (I.STOCK_MINIMO - I.STOCK_ACTUAL) AS CANTIDAD_FALTANTE
    FROM INVENTARIO I
    JOIN PRODUCTOS P ON I.ID_PRODUCTO = P.ID_PRODUCTO
    WHERE I.STOCK_ACTUAL <= I.STOCK_MINIMO
    ORDER BY CANTIDAD_FALTANTE DESC;
END ;
DELIMITER ;

--Estos sp son para mostrar antes de colocar datos en productos

--PARA INSERTAR PRODUSTOS

DELIMITER //

DROP PROCEDURE IF EXISTS PARA_INSERTAR_PRODUCTO;

CREATE PROCEDURE PARA_INSERTAR_PRODUCTO()
BEGIN
    -- Primer conjunto de resultados: Las categorías ordenadas de forma descendente
    SELECT ID_CATEGORIA, NOMBRE 
    FROM CATEGORIAS 
    ORDER BY ID_CATEGORIA ASC;

    -- Segundo conjunto de resultados: Las marcas ordenadas de forma descendente
    SELECT ID_MARCA, NOMBRE 
    FROM MARCAS 
    ORDER BY ID_MARCA ASC;
END;

DELIMITER;
CALL PARA_INSERTAR_PRODUCTO();



--PARA LA ACTUALIZACION DE LOS DATOS 
DELIMITER//
DROP PROCEDURE IF EXISTS PARA_ACTUALIZARDATOS;

CREATE PROCEDURE PARA_ACTUALIZARDATOS()
BEGIN

SELECT 
    P.ID_PRODUCTO,
    P.NOMBRE AS PRODUCTO,
    P.PRECIO,
    C.ID_CATEGORIA,
    C.NOMBRE AS CATEGORIA,
    M.ID_MARCA,
    M.NOMBRE AS MARCA
FROM 
    PRODUCTOS AS P
LEFT JOIN 
    CATEGORIAS AS C 
    ON P.ID_CATEGORIA = C.ID_CATEGORIA
LEFT JOIN 
    MARCAS AS M 
    ON P.ID_MARCA = M.ID_MARCA;

END;

CALL PARA_ACTUALIZARDATOS(); 

DELIMITER;

USE BALBU_TECH;


SELECT * FROM PRODUCTOS;

