-- =============================================================================
-- test_cancelacion_p4.sql — Suite e2e de cancelación/anulación (Parte 4).
-- Cubre: cancelar EN_PROCESO sin pagos (repone stock), con pagos (error),
-- REALIZADA (error), anular pago (reabre + borra bono PENDIENTE),
-- anular en CANCELADA (error).
-- Uso:  mariadb --force -h 127.0.0.1 -uroot -pXXX BALBU_TECH < test_cancelacion_p4.sql
-- Cada bloque va en SU PROPIA transaccion con START TRANSACTION ... ROLLBACK:
-- SP_CANCELAR_VENTA/SP_ANULAR_PAGO respetan la transaccion abierta
-- (patron transaccion-propia) y todo revierte. Residuo esperado: 0.
-- Pre: bash db/seed-admin.sh (empleado admin ID 1) + seed-catalogo (marca 1).
-- OJO: no usar subselects a VENTAS dentro de INSERT/UPDATE que disparen
-- triggers sobre VENTAS (ERROR 1442); usar @vars asignadas antes.
-- Fecha: 09/10/2026.
-- =============================================================================

-- --- K1: cancelar EN_PROCESO sin pagos repone stock ---------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TK1','descripcion larga k1');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PK1');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRK1','descripcion producto k1',50.00,'CK1',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TK1'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PK1'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLK1','0','k1@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLK1'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CK1';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TK1');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 2, 50.00);
SELECT STOCK_ACTUAL FROM INVENTARIO WHERE ID_PRODUCTO = @p;
-- EXPECT: EXITO/cancelada; stock vuelve a 10.
CALL SP_CANCELAR_VENTA(@v, 1);
SELECT ESTADO FROM VENTAS WHERE ID_VENTA = @v;
SELECT STOCK_ACTUAL FROM INVENTARIO WHERE ID_PRODUCTO = @p;
ROLLBACK;

-- --- K2: con pagos no se cancela ------------------------------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TK2','descripcion larga k2');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PK2');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRK2','descripcion producto k2',50.00,'CK2',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TK2'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PK2'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLK2','0','k2@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLK2'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CK2';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TK2');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 1, 50.00);
-- Pago PARCIAL para que siga EN_PROCESO pero con pagos.
CALL 24_SP_REGISTRAR_PAGO(@v, 1, 20.00, 1, 20.00);
-- EXPECT: ERROR: LA VENTA TIENE PAGOS REGISTRADOS, NO SE PUEDE CANCELAR.
CALL SP_CANCELAR_VENTA(@v, 1);
ROLLBACK;

-- --- K3: REALIZADA no se cancela ---------------------------------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TK3','descripcion larga k3');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PK3');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRK3','descripcion producto k3',50.00,'CK3',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TK3'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PK3'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLK3','0','k3@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLK3'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CK3';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TK3');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 1, 50.00);
CALL 24_SP_REGISTRAR_PAGO(@v, 1, 50.00, 1, 50.00);
-- EXPECT: ERROR: SOLO SE PUEDEN CANCELAR VENTAS EN PROCESO.
CALL SP_CANCELAR_VENTA(@v, 1);
ROLLBACK;

-- --- K4: anular pago reabre y borra el bono PENDIENTE --------------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TK4','descripcion larga k4');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PK4');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRK4','descripcion producto k4',100.00,'CK4',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TK4'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PK4'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLK4','0','k4@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLK4'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CK4';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TK4');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 1, 100.00);
CALL 24_SP_REGISTRAR_PAGO(@v, 1, 100.00, 1, 100.00);
SELECT @pg := ID_PAGO FROM PAGOS WHERE ID_VENTA = @v;
-- EXPECT: venta vuelve a EN_PROCESO y el bono PENDIENTE desaparece.
CALL SP_ANULAR_PAGO(@pg, 1);
SELECT ESTADO FROM VENTAS WHERE ID_VENTA = @v;
SELECT COUNT(*) FROM BONOS_EMPLEADOS WHERE ID_EMPLEADO = 1;
ROLLBACK;

-- --- K5: anular pago de venta CANCELADA se rechaza --------------------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TK5','descripcion larga k5');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PK5');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRK5','descripcion producto k5',50.00,'CK5',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TK5'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PK5'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLK5','0','k5@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLK5'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CK5';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TK5');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 1, 50.00);
CALL SP_CANCELAR_VENTA(@v, 1);
-- La venta esta CANCELADA y sin pagos: anular un pago inexistente da error.
-- EXPECT: ERROR (el pago no existe).
CALL SP_ANULAR_PAGO(999999, 1);
ROLLBACK;
