-- =============================================================================
-- test_cobro_p2.sql — Suite e2e del cobro (Parte 2).
-- Cubre: pago exacto, vuelto, recibido<monto, sobre-saldo en cerrada.
-- Uso:  mariadb --force -h 127.0.0.1 -uroot -pXXX BALBU_TECH < test_cobro_p2.sql
--       (--force = continuar tras los SIGNAL esperados de cada candado.)
-- Cada bloque va en SU PROPIA transaccion con START TRANSACTION ... ROLLBACK:
-- los SPs de cobro no abren transaccion propia si ya hay una abierta, asi que
-- todo revierte. Residuo esperado: 0 en todas las tablas.
-- Pre: bash db/seed-admin.sh (empleado admin ID 1) + seed-catalogo (marca 1).
-- OJO: no usar subselects a VENTAS dentro del INSERT a DETALLES_VENTA
-- (dispara ERROR 1442 por el trigger que actualiza VENTAS); usar @vars.
-- Fecha: 09/10/2026 (P9 verificado aqui bloque por bloque).
-- =============================================================================

-- --- C1: pago exacto cierra y crea UN bono del 1% --------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TC1','descripcion larga c1');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PC1');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRC1','descripcion producto c1',100.00,'CC1',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TC1'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PC1'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLC1','0','c1@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLC1'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CC1';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TC1');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 1, 100.00);
-- EXPECT: EXITO sin vuelto; venta REALIZADA; 1 bono de 1.00 PENDIENTE.
CALL 24_SP_REGISTRAR_PAGO(@v, 1, 100.00, 1, 100.00);
SELECT ESTADO FROM VENTAS WHERE ID_VENTA = @v;
SELECT COUNT(*), SUM(MONTO) FROM BONOS_EMPLEADOS WHERE ID_EMPLEADO = 1;
ROLLBACK;

-- --- C2: vuelto (100 aplicado, 150 recibido) -------------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TC2','descripcion larga c2');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PC2');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRC2','descripcion producto c2',100.00,'CC2',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TC2'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PC2'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLC2','0','c2@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLC2'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CC2';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TC2');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 1, 100.00);
-- EXPECT: EXITO con (VUELTO 50.00); fila PAGOS (100.00/150.00).
CALL 24_SP_REGISTRAR_PAGO(@v, 1, 100.00, 1, 150.00);
SELECT MONTO, MONTO_RECIBIDO FROM PAGOS WHERE ID_VENTA = @v;
ROLLBACK;

-- --- C3: recibido < monto se rechaza ------------------------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TC3','descripcion larga c3');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PC3');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRC3','descripcion producto c3',100.00,'CC3',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TC3'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PC3'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLC3','0','c3@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLC3'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CC3';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TC3');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 1, 100.00);
-- EXPECT: ERROR: EL MONTO RECIBIDO ES MENOR QUE EL PAGO.
CALL 24_SP_REGISTRAR_PAGO(@v, 1, 100.00, 1, 30.00);
ROLLBACK;

-- --- C4: sobre-saldo en venta cerrada se rechaza --------------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TC4','descripcion larga c4');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PC4');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRC4','descripcion producto c4',100.00,'CC4',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TC4'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PC4'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLC4','0','c4@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLC4'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CC4';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TC4');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 1, 100.00);
CALL 24_SP_REGISTRAR_PAGO(@v, 1, 100.00, 1, 100.00);
-- EXPECT: ERROR: LA VENTA NO ESTA ABIERTA PARA RECIBIR PAGOS.
CALL 24_SP_REGISTRAR_PAGO(@v, 1, 10.00, 1, 10.00);
ROLLBACK;
