-- =============================================================================
-- test_devoluciones_p5.sql — Suite e2e de devoluciones/garantías (Parte 5).
-- Cubre: registrar PENDIENTE sin tocar stock, aprobar (reintegra stock),
-- rechazar (concatena motivo, libera cuota), reprocesar (error),
-- sobre-devolver más de lo comprado (error).
-- Uso:  mariadb --force -h 127.0.0.1 -uroot -pXXX BALBU_TECH < test_devoluciones_p5.sql
-- Cada bloque va en SU PROPIA transaccion con START TRANSACTION ... ROLLBACK.
-- Residuo esperado: 0 en todas las tablas.
-- Pre: bash db/seed-admin.sh (empleado admin ID 1) + seed-catalogo (marca 1).
-- OJO: no usar subselects a VENTAS dentro de INSERT/UPDATE que disparen
-- triggers sobre VENTAS (ERROR 1442); usar @vars asignadas antes.
-- Fecha: 09/10/2026.
-- =============================================================================

-- --- T1: registrar deja PENDIENTE sin tocar stock ---------------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TT1','descripcion larga t1');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PT1');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRT1','descripcion producto t1',40.00,'CT1',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TT1'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PT1'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLT1','0','t1@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLT1'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CT1';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TT1');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 2, 40.00);
SELECT @d := ID_DETALLE_VENTA FROM DETALLES_VENTA ORDER BY ID_DETALLE_VENTA DESC LIMIT 1;
-- EXPECT: EXITO + fila PENDIENTE; stock sigue en 8 (10-2).
CALL SP_REGISTRAR_DEVOLUCION(@d, NULL, 1, 1, 'falla de fabrica', 'BUENO');
SELECT ESTADO, CANTIDAD FROM DEVOLUCIONES ORDER BY ID_DEVOLUCION DESC LIMIT 1;
SELECT STOCK_ACTUAL FROM INVENTARIO WHERE ID_PRODUCTO = @p;
ROLLBACK;

-- --- T2: aprobar reintegra stock ---------------------------------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TT2','descripcion larga t2');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PT2');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRT2','descripcion producto t2',40.00,'CT2',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TT2'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PT2'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLT2','0','t2@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLT2'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CT2';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TT2');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 2, 40.00);
SELECT @d := ID_DETALLE_VENTA FROM DETALLES_VENTA ORDER BY ID_DETALLE_VENTA DESC LIMIT 1;
CALL SP_REGISTRAR_DEVOLUCION(@d, NULL, 1, 1, 'falla de fabrica', 'BUENO');
SELECT @r := ID_DEVOLUCION FROM DEVOLUCIONES ORDER BY ID_DEVOLUCION DESC LIMIT 1;
-- EXPECT: APROBADA + stock 8 -> 9.
CALL 25_SP_PROCESAR_DEVOLUCION(@r, 'APROBADA');
SELECT ESTADO FROM DEVOLUCIONES WHERE ID_DEVOLUCION = @r;
SELECT STOCK_ACTUAL FROM INVENTARIO WHERE ID_PRODUCTO = @p;
ROLLBACK;

-- --- T3: rechazar concatena motivo y libera cuota -------------------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TT3','descripcion larga t3');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PT3');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRT3','descripcion producto t3',40.00,'CT3',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TT3'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PT3'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLT3','0','t3@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLT3'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CT3';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TT3');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 1, 40.00);
SELECT @d := ID_DETALLE_VENTA FROM DETALLES_VENTA ORDER BY ID_DETALLE_VENTA DESC LIMIT 1;
CALL SP_REGISTRAR_DEVOLUCION(@d, NULL, 1, 1, 'no era lo esperado', 'BUENO');
SELECT @r := ID_DEVOLUCION FROM DEVOLUCIONES ORDER BY ID_DEVOLUCION DESC LIMIT 1;
-- EXPECT: RECHAZADA con motivo concatenado; stock intacto en 9.
CALL 26_SP_RECHAZAR_DEVOLUCION(@r, 'fuera de plazo');
SELECT ESTADO, MOTIVO FROM DEVOLUCIONES WHERE ID_DEVOLUCION = @r;
SELECT STOCK_ACTUAL FROM INVENTARIO WHERE ID_PRODUCTO = @p;
ROLLBACK;

-- --- T4: reprocesar una APROBADA se rechaza ----------------------------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TT4','descripcion larga t4');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PT4');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRT4','descripcion producto t4',40.00,'CT4',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TT4'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PT4'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLT4','0','t4@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLT4'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CT4';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TT4');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 1, 40.00);
SELECT @d := ID_DETALLE_VENTA FROM DETALLES_VENTA ORDER BY ID_DETALLE_VENTA DESC LIMIT 1;
CALL SP_REGISTRAR_DEVOLUCION(@d, NULL, 1, 1, 'falla', 'BUENO');
SELECT @r := ID_DEVOLUCION FROM DEVOLUCIONES ORDER BY ID_DEVOLUCION DESC LIMIT 1;
CALL 25_SP_PROCESAR_DEVOLUCION(@r, 'APROBADA');
-- EXPECT: ERROR: ESTA DEVOLUCION YA FUE PROCESADA.
CALL 25_SP_PROCESAR_DEVOLUCION(@r, 'REEMBOLSADA');
ROLLBACK;

-- --- T5: sobre-devolver mas de lo comprado se rechaza ----------------------------------------------
START TRANSACTION;
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES ('TT5','descripcion larga t5');
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PT5');
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CODIGO, ID_MARCA, ID_CATEGORIA, ID_PROVEEDOR)
VALUES ('PRT5','descripcion producto t5',40.00,'CT5',1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE='TT5'),
  (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE NOMBRE='PT5'));
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL) VALUES ('CLT5','0','t5@t.co');
INSERT INTO VENTAS (ID_CLIENTE, ID_EMPLEADO, TOTAL)
VALUES ((SELECT ID_CLIENTE FROM CLIENTES WHERE NOMBRE='CLT5'), 1, 0);
SELECT @v := ID_VENTA FROM VENTAS ORDER BY ID_VENTA DESC LIMIT 1;
SELECT @p := ID_PRODUCTO FROM PRODUCTOS WHERE CODIGO='CT5';
INSERT INTO INVENTARIO (ID_PRODUCTO, STOCK_ACTUAL, STOCK_MINIMO, UBICACION)
VALUES (@p, 10, 1, 'TT5');
INSERT INTO DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (@v, @p, 1, 40.00);
SELECT @d := ID_DETALLE_VENTA FROM DETALLES_VENTA ORDER BY ID_DETALLE_VENTA DESC LIMIT 1;
-- EXPECT: ERROR (cantidad 5 > comprada 1).
CALL SP_REGISTRAR_DEVOLUCION(@d, NULL, 1, 5, 'muchas', 'BUENO');
ROLLBACK;
