#!/bin/bash
# Verifica que existan todos los stored procedures que la app C++ invoca.
# Uso: docker compose exec app bash db/check-app-sps.sh
# Extraidos de grep 'CALL ...' en *.cpp
set -u
DB_HOST="${DB_HOST:-db}"
DB_PORT="${DB_PORT:-3306}"
DB_NAME="${DB_NAME:-BALBU_TECH}"
DB_USER="${DB_USER:-root}"
DB_PASSWORD="${DB_PASSWORD:-${MARIADB_ROOT_PASSWORD:-linux01}}"
Q() { mariadb -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -p"$DB_PASSWORD" --database="$DB_NAME" -N -e "$1"; }
missing=0
while read -r p; do
  [ -z "$p" ] && continue
  c=$(Q "SELECT COUNT(*) FROM information_schema.routines WHERE routine_schema='$DB_NAME' AND ROUTINE_NAME='$p'")
  if [ "$c" = "0" ]; then echo "FALTA: $p"; missing=$((missing+1)); fi
done <<'SPS'
SP_GET_USUARIO_LOGIN
SP_INSERTAR_CATEGORIA
SP_ACTUALIZAR_CATEGORIA
SP_TOGGLE_ESTADO_CATEGORIA
SP_BUSCAR_CATEGORIA
SP_LISTAR_CATEGORIAS
SP_INSERTAR_MARCA
SP_ACTUALIZAR_MARCA
SP_TOGGLE_ESTADO_MARCA
SP_BUSCAR_MARCA
SP_LISTAR_MARCAS
SP_INSERTAR_CLIENTES
SP_ACTUALIZAR_CLIENTES
SP_TOGGLE_ESTADO_CLIENTES
SP_INSERTAR_PROVEEDOR
SP_ACTUALIZAR_PROVEEDOR
SP_TOGGLE_ESTADO_PROVEEDOR
SP_LISTAR_PROVEEDORES
SP_INSERTAR_EMPLEADO
SP_ACTUALIZAR_EMPLEADO
SP_DESPEDIR_EMPLEADO
SP_REACTIVAR_EMPLEADO
SP_INSERTAR_ROL
SP_ACTUALIZAR_ROL
SP_BUSCAR_ROLES
SP_INSERTAR_USUARIO
SP_ACTUALIZAR_USUARIO
SP_TOGGLE_ESTADO_USUARIO
SP_BUSCAR_USUARIOS
SP_CAMBIAR_CLAVE_USUARIO
SP_INSERTAR_METODO_PAGO
SP_ACTUALIZAR_METODO_PAGO
SP_TOGGLE_ESTADO_METODO_PAGO
SP_BUSCAR_METODOS_PAGO
SP_INSERTAR_PRODUCTO
SP_ACTUALIZAR_PRODUCTOS
SP_TOGGLE_ESTADO_PRODUCTOS
SP_CONSULTAR_PRODUCTOS_FILTRADO
SP_CONSULTAR_INVENTARIO
SP_REPORTE_STOCK_CRITICO
PARA_INSERTAR_PRODUCTO
PARA_ACTUALIZARDATOS
PARA_ACTIVARODESACTIVAR_PROC
PARA_INSERTAR_USUARIOS
PARA_ACTUALIZAR_USUARIOS
PARA_ACT_DESAC_USUARIOS
SPS
echo "Faltantes: $missing"
